### ISSUE TITLE
Any reason to to set <SPACE> as leader key by default?

### ISSUE THREAD

**Issue by biocyberman** [taohex/navim#4]
Yeah, it is a big key, and I like it. Should I do it or you have some reason not to do so?

**Comment by taohex** [comment]
I appreciate setting `<Space>` as leader key. [Spacemacs](https://github.com/syl20bnr/spacemacs) does great job for emacs users. It binds `<Space>` globally, and `,` for specific format. This can avoid conflict.
I am doing some experiment to change the default key actually, but it needs a list of carefully-chosen key bindings. It may take a long time for test. On the other hand, `,` is the default key for most vim users, I don't know is it right to change the habits.

**Comment by biocyberman** [comment]
I am also a spacemacs user :) Therefore I also enjoy the way they setup <SPACE> for leader key, and `,` for context-sensitive commands. I think it will not upset users who use `,` as the leader key if  you have good documentation, and can show the convenience of <SPACE> leader. 

Side track: why do I need vim/nvim when we already know about spacemacs? ;-) I still want to use vim for its light-weight when I edit random files. And it is also beneficial to be better at vim editing commands anyway.

**Comment by taohex** [comment]
I have changed leader key to `<Space>`. All key bindings is reorganized. Please refer to `README.md`.
